services:

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "hasaan"  
    ports:
      - "3307:3306"


  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
