[project]
name = "lab-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "awscli>=1.42.45",
    "boto3>=1.40.45",
    "botocore>=1.40.45",
    "fpdf>=1.7.2",
    "reportlab>=4.4.4",
    "requests>=2.32.5",
]
